import { describe, expect, it } from 'vitest'
import { HTMLDocumentRenderer } from '../../src/output/HTMLDocumentRenderer.js'
import { BrandThemeLoader } from '../../src/output/BrandThemeLoader.js'
import { UIPrototypeRenderer } from '../../src/output/UIPrototypeRenderer.js'

describe('HTMLDocumentRenderer', () => {
  // ========================================================================
  // renderSpec
  // ========================================================================

  describe('renderSpec', () => {
    const renderer = new HTMLDocumentRenderer({ title: 'Test Spec', lang: 'zh' })
    const specData = {
      id: 'SPEC-20260421-0001',
      title: 'User Authentication',
      what: 'Implement OAuth2 login flow with Google and GitHub providers',
      successCriteria: ['User can login via Google', 'User can login via GitHub', 'Session persists for 7 days'],
      outOfScope: ['Password-based login', 'Two-factor authentication'],
      edgeCases: ['OAuth provider timeout', 'Multiple accounts same email'],
      northStar: 'Users can authenticate with zero friction',
      ambiguityScore: 0.12,
    }

    it('generates valid HTML document', () => {
      const html = renderer.renderSpec(specData)
      expect(html).toContain('<!DOCTYPE html>')
      expect(html).toContain('</html>')
      expect(html).toContain('<head>')
      expect(html).toContain('</head>')
      expect(html).toContain('<body>')
      expect(html).toContain('</body>')
    })

    it('contains document title', () => {
      const html = renderer.renderSpec(specData)
      expect(html).toContain('User Authentication')
      expect(html).toContain('SCALE Engine')
    })

    it('contains spec ID in meta tags', () => {
      const html = renderer.renderSpec(specData)
      expect(html).toContain('SPEC-20260421-0001')
    })

    it('renders success criteria as checklist', () => {
      const html = renderer.renderSpec(specData)
      expect(html).toContain('User can login via Google')
      expect(html).toContain('User can login via GitHub')
      expect(html).toContain('Session persists for 7 days')
      expect(html).toContain('checklist')
    })

    it('renders out of scope items', () => {
      const html = renderer.renderSpec(specData)
      expect(html).toContain('Password-based login')
      expect(html).toContain('Two-factor authentication')
    })

    it('renders edge cases', () => {
      const html = renderer.renderSpec(specData)
      expect(html).toContain('OAuth provider timeout')
    })

    it('renders ambiguity score in meta', () => {
      const html = renderer.renderSpec(specData)
      expect(html).toContain('0.12')
    })

    it('includes inline CSS (no external stylesheets)', () => {
      const html = renderer.renderSpec(specData)
      expect(html).toContain('<style>')
      expect(html).not.toContain('<link rel="stylesheet"')
    })

    it('uses dark theme by default', () => {
      const html = renderer.renderSpec(specData)
      expect(html).toContain('#0f0f0f')
      expect(html).toContain('#00ff88')
    })

    it('includes TOC navigation when interactive', () => {
      const html = renderer.renderSpec(specData)
      expect(html).toContain('doc-toc')
      expect(html).toContain('#overview')
      expect(html).toContain('#success-criteria')
    })

    it('escapes HTML in user content', () => {
      const xssData = {
        ...specData,
        what: '<script>alert("xss")</script>',
        title: 'Test <img onerror="alert(1)">',
      }
      const html = renderer.renderSpec(xssData)
      expect(html).not.toContain('<script>alert("xss")</script>')
      expect(html).toContain('&lt;script&gt;')
    })

    it('includes print-friendly CSS', () => {
      const html = renderer.renderSpec(specData)
      expect(html).toContain('@media print')
    })

    it('includes interactive script when enabled', () => {
      const html = renderer.renderSpec(specData)
      expect(html).toContain('<script>')
      expect(html).toContain('IntersectionObserver')
    })

    it('respects lang attribute', () => {
      const html = renderer.renderSpec(specData)
      expect(html).toContain('lang="zh"')
    })

    it('includes footer with generation info', () => {
      const html = renderer.renderSpec(specData)
      expect(html).toContain('Generated by SCALE Engine')
      expect(html).toContain('Ctrl+P to print as PDF')
    })
  })

  // ========================================================================
  // renderPlan
  // ========================================================================

  describe('renderPlan', () => {
    const renderer = new HTMLDocumentRenderer({ title: 'Test Plan', lang: 'en' })
    const planData = {
      id: 'PLAN-20260421-0001',
      specId: 'SPEC-20260421-0001',
      approach: 'Use Next.js with server-side rendering for SEO optimization',
      techChoices: [
        { decision: 'Next.js', rationale: 'SSR support and React ecosystem' },
        { decision: 'Prisma', rationale: 'Type-safe database access', alternatives: ['Drizzle', 'TypeORM'] },
      ],
      modules: [
        { path: 'src/auth/login.ts', action: 'create' as const, reason: 'OAuth2 flow implementation' },
        { path: 'src/auth/session.ts', action: 'modify' as const, reason: 'Add session persistence' },
        { path: 'src/legacy/auth.js', action: 'delete' as const, reason: 'Replace legacy auth' },
      ],
      rollbackStrategy: 'Revert to previous auth module and restore legacy auth.js',
      estimatedComplexity: 7,
    }

    it('generates valid HTML document', () => {
      const html = renderer.renderPlan(planData)
      expect(html).toContain('<!DOCTYPE html>')
      expect(html).toContain('</html>')
    })

    it('contains plan ID', () => {
      const html = renderer.renderPlan(planData)
      expect(html).toContain('PLAN-20260421-0001')
    })

    it('renders approach section', () => {
      const html = renderer.renderPlan(planData)
      expect(html).toContain('Next.js with server-side rendering')
    })

    it('renders tech choices table', () => {
      const html = renderer.renderPlan(planData)
      expect(html).toContain('Next.js')
      expect(html).toContain('SSR support')
      expect(html).toContain('Prisma')
    })

    it('renders tech choice alternatives', () => {
      const html = renderer.renderPlan(planData)
      expect(html).toContain('Drizzle')
      expect(html).toContain('TypeORM')
    })

    it('renders modules with action badges', () => {
      const html = renderer.renderPlan(planData)
      expect(html).toContain('src/auth/login.ts')
      expect(html).toContain('create')
      expect(html).toContain('modify')
      expect(html).toContain('delete')
    })

    it('renders rollback strategy', () => {
      const html = renderer.renderPlan(planData)
      expect(html).toContain('Revert to previous auth module')
    })

    it('renders complexity metric', () => {
      const html = renderer.renderPlan(planData)
      expect(html).toContain('7/10')
    })

    it('renders TOC with plan sections', () => {
      const html = renderer.renderPlan(planData)
      expect(html).toContain('#approach')
      expect(html).toContain('#tech-choices')
      expect(html).toContain('#modules')
      expect(html).toContain('#rollback')
    })
  })

  // ========================================================================
  // renderReview
  // ========================================================================

  describe('renderReview', () => {
    const renderer = new HTMLDocumentRenderer({ title: 'Test Review' })

    it('renders review with findings', () => {
      const html = renderer.renderReview({
        id: 'REVIEW-001',
        title: 'Code Review',
        timestamp: '2026-05-14T10:00:00Z',
        findings: [
          { severity: 'CRITICAL', file: 'src/auth.ts', line: 42, message: 'Hardcoded API key' },
          { severity: 'HIGH', file: 'src/db.ts', message: 'SQL injection risk' },
          { severity: 'LOW', file: 'src/util.ts', line: 10, message: 'Unused import' },
        ],
        passed: false,
      })

      expect(html).toContain('CRITICAL')
      expect(html).toContain('Hardcoded API key')
      expect(html).toContain('src/auth.ts:42')
      expect(html).toContain('FAIL')
    })

    it('renders passing review', () => {
      const html = renderer.renderReview({
        id: 'REVIEW-002',
        title: 'Clean Review',
        timestamp: '2026-05-14T10:00:00Z',
        findings: [],
        passed: true,
      })

      expect(html).toContain('PASS')
      expect(html).toContain('No findings')
    })

    it('renders spec coverage when provided', () => {
      const html = renderer.renderReview({
        id: 'REVIEW-003',
        title: 'Review with Coverage',
        timestamp: '2026-05-14T10:00:00Z',
        findings: [],
        passed: true,
        specCoverage: 0.85,
      })

      expect(html).toContain('85%')
    })
  })

  // ========================================================================
  // renderReport
  // ========================================================================

  describe('renderReport', () => {
    const renderer = new HTMLDocumentRenderer()

    it('renders report with sections', () => {
      const html = renderer.renderReport({
        type: 'delivery',
        title: 'Delivery Report',
        timestamp: '2026-05-14T10:00:00Z',
        sections: [
          { heading: 'Summary', content: '<p>All tasks completed</p>' },
          { heading: 'Metrics', content: '<p>461 tests passing</p>' },
        ],
        metrics: { tests: 461, coverage: '85%' },
      })

      expect(html).toContain('Delivery Report')
      expect(html).toContain('All tasks completed')
      expect(html).toContain('461')
      expect(html).toContain('85%')
    })
  })

  // ========================================================================
  // renderContent
  // ========================================================================

  describe('renderContent', () => {
    const renderer = new HTMLDocumentRenderer()

    it('renders arbitrary content', () => {
      const html = renderer.renderContent('Custom Page', '<p>Hello World</p>', 'CUSTOM')
      expect(html).toContain('Custom Page')
      expect(html).toContain('Hello World')
      expect(html).toContain('CUSTOM')
    })
  })

  // ========================================================================
  // Theme options
  // ========================================================================

  describe('theme options', () => {
    it('supports light theme', () => {
      const renderer = new HTMLDocumentRenderer({ theme: 'light' })
      const html = renderer.renderSpec({
        id: 'SPEC-001', title: 'Test', what: 'Test',
        successCriteria: [], outOfScope: [], edgeCases: [], northStar: '',
      })
      expect(html).toContain('#ffffff')
    })

    it('supports auto theme with prefers-color-scheme', () => {
      const renderer = new HTMLDocumentRenderer({ theme: 'auto' })
      const html = renderer.renderSpec({
        id: 'SPEC-001', title: 'Test', what: 'Test',
        successCriteria: [], outOfScope: [], edgeCases: [], northStar: '',
      })
      expect(html).toContain('prefers-color-scheme')
    })

    it('disables interactive TOC element when set', () => {
      const renderer = new HTMLDocumentRenderer({ interactive: false })
      const html = renderer.renderSpec({
        id: 'SPEC-001', title: 'Test', what: 'Test',
        successCriteria: ['criterion'], outOfScope: [], edgeCases: [], northStar: '',
      })
      // The TOC <aside> element should not be rendered
      expect(html).not.toContain('<aside class="doc-toc">')
      // The interactive script should not be included
      expect(html).not.toContain('<script>')
    })

    it('disables print-friendly hint when set', () => {
      const renderer = new HTMLDocumentRenderer({ printFriendly: false })
      const html = renderer.renderSpec({
        id: 'SPEC-001', title: 'Test', what: 'Test',
        successCriteria: [], outOfScope: [], edgeCases: [], northStar: '',
      })
      expect(html).not.toContain('Ctrl+P to print as PDF')
    })
  })

  // ========================================================================
  // writeToFile
  // ========================================================================

  describe('writeToFile', () => {
    it('exports writeToFile method', () => {
      const renderer = new HTMLDocumentRenderer()
      expect(typeof renderer.writeToFile).toBe('function')
    })
  })
})

// ============================================================================
// BrandThemeLoader
// ============================================================================

describe('BrandThemeLoader', () => {
  const loader = new BrandThemeLoader()

  it('lists built-in brands', () => {
    const brands = loader.listAvailableBrands()
    expect(brands).toContain('vercel')
    expect(brands).toContain('stripe')
    expect(brands).toContain('notion')
    expect(brands).toContain('linear')
    expect(brands).toContain('github')
  })

  it('loads vercel brand', () => {
    const theme = loader.loadBrand('vercel')
    expect(theme).not.toBeNull()
    expect(theme!.name).toBe('vercel')
    expect(theme!.displayName).toBe('Vercel')
    expect(theme!.colors.primary).toBe('#000000')
  })

  it('loads stripe brand', () => {
    const theme = loader.loadBrand('stripe')
    expect(theme).not.toBeNull()
    expect(theme!.colors.primary).toBe('#635bff')
    expect(theme!.colors.bg).toBe('#0a2540')
  })

  it('loads notion brand (light theme)', () => {
    const theme = loader.loadBrand('notion')
    expect(theme).not.toBeNull()
    expect(theme!.colors.bg).toBe('#ffffff')
    expect(theme!.colors.fg).toBe('#37352f')
  })

  it('loads github brand', () => {
    const theme = loader.loadBrand('github')
    expect(theme).not.toBeNull()
    expect(theme!.colors.primary).toBe('#0969da')
  })

  it('returns null for unknown brand', () => {
    const theme = loader.loadBrand('unknown-brand-12345')
    expect(theme).toBeNull()
  })

  it('hasBrand returns true for built-in brands', () => {
    expect(loader.hasBrand('vercel')).toBe(true)
    expect(loader.hasBrand('stripe')).toBe(true)
    expect(loader.hasBrand('nonexistent')).toBe(false)
  })

  it('generates CSS variables from brand theme', () => {
    const theme = loader.loadBrand('vercel')!
    const css = loader.getCSSVariables(theme)
    expect(css).toContain('--brand-primary:')
    expect(css).toContain('#000000')
    expect(css).toContain('--brand-bg:')
  })

  it('generates override CSS for brand', () => {
    const theme = loader.loadBrand('linear')!
    const css = loader.getOverrideCSS(theme)
    expect(css).toContain('--bg:')
    expect(css).toContain('--accent:')
  })

  it('loadBrand returns Linear theme', () => {
    const theme = loader.loadBrand('linear')
    expect(theme).not.toBeNull()
    expect(theme!.name).toBe('linear')
    expect(theme!.colors.primary).toBe('#5e6ad2')
  })
})

// ============================================================================
// UIPrototypeRenderer
// ============================================================================

describe('UIPrototypeRenderer', () => {
  const renderer = new UIPrototypeRenderer()

  describe('renderWireframe', () => {
    it('renders empty state', () => {
      const html = renderer.renderWireframe([])
      expect(html).toContain('<!DOCTYPE html>')
      expect(html).toContain('Empty Prototype')
    })

    it('renders single page', () => {
      const html = renderer.renderWireframe([{
        name: 'Home',
        title: 'Home Page',
        layout: 'single-column',
        components: [
          { type: 'hero', title: 'Welcome', data: { subtitle: 'Get started' } },
          { type: 'card', title: 'Feature 1', data: { content: 'Description' } },
        ],
      }])
      expect(html).toContain('Home Page')
      expect(html).toContain('Welcome')
      expect(html).toContain('Feature 1')
    })

    it('renders multi-page with tabs', () => {
      const html = renderer.renderWireframe([
        { name: 'Page 1', title: 'First', layout: 'single-column', components: [{ type: 'card', title: 'Card A' }] },
        { name: 'Page 2', title: 'Second', layout: 'single-column', components: [{ type: 'card', title: 'Card B' }] },
      ])
      expect(html).toContain('Page 1')
      expect(html).toContain('Page 2')
      expect(html).toContain('proto-tab')
      expect(html).toContain('showPage')
    })

    it('renders table component', () => {
      const html = renderer.renderWireframe([{
        name: 'Data',
        title: 'Data Page',
        layout: 'single-column',
        components: [{
          type: 'table',
          title: 'Users',
          data: { headers: ['Name', 'Email'], rows: [['Alice', 'alice@x.com'], ['Bob', 'bob@x.com']] },
        }],
      }])
      expect(html).toContain('Users')
      expect(html).toContain('Name')
      expect(html).toContain('Alice')
      expect(html).toContain('bob@x.com')
    })

    it('renders form component', () => {
      const html = renderer.renderWireframe([{
        name: 'Form',
        title: 'Registration',
        layout: 'single-column',
        components: [{
          type: 'form',
          title: 'Sign Up',
          data: { fields: [{ label: 'Email', type: 'email', placeholder: 'Enter email' }] },
        }],
      }])
      expect(html).toContain('Sign Up')
      expect(html).toContain('Enter email')
    })

    it('renders list component', () => {
      const html = renderer.renderWireframe([{
        name: 'List',
        title: 'Items',
        layout: 'single-column',
        components: [{
          type: 'list',
          title: 'Features',
          data: { items: ['Auth', 'Dashboard', 'API'] },
        }],
      }])
      expect(html).toContain('Features')
      expect(html).toContain('Auth')
      expect(html).toContain('Dashboard')
    })

    it('renders two-column layout', () => {
      const html = renderer.renderWireframe([{
        name: 'TwoCol',
        title: 'Two Column',
        layout: 'two-column',
        components: [{ type: 'card', title: 'Left' }, { type: 'card', title: 'Right' }],
      }])
      expect(html).toContain('proto-layout-2col')
    })

    it('renders sidebar layout', () => {
      const html = renderer.renderWireframe([{
        name: 'Sidebar',
        title: 'Sidebar Layout',
        layout: 'sidebar',
        components: [],
        navigation: [
          { label: 'Home', href: '/', active: true },
          { label: 'Settings', href: '/settings' },
        ],
      }])
      expect(html).toContain('proto-topnav')
      expect(html).toContain('Home')
      expect(html).toContain('Settings')
    })
  })

  describe('renderDashboard', () => {
    it('renders dashboard with widgets', () => {
      const html = renderer.renderDashboard({
        title: 'Admin Dashboard',
        description: 'System overview',
        nav: [
          { label: 'Overview', href: '/', active: true },
          { label: 'Users', href: '/users' },
        ],
        widgets: [
          { title: 'Total Users', type: 'metric', data: { value: '1,234', label: 'users' } },
          { title: 'Status', type: 'status', data: { ok: true, message: 'All systems operational' } },
          { title: 'Recent', type: 'list', data: { items: ['Event A', 'Event B'] }, size: 'large' },
        ],
      })
      expect(html).toContain('Admin Dashboard')
      expect(html).toContain('proto-sidebar')
      expect(html).toContain('Total Users')
      expect(html).toContain('1,234')
      expect(html).toContain('All systems operational')
      expect(html).toContain('widget-lg')
    })
  })

  describe('renderComponent', () => {
    it('renders component collection', () => {
      const html = renderer.renderComponent([
        { type: 'header', title: 'Page Header' },
        { type: 'card', title: 'Info Card', data: { content: 'Details here' } },
      ])
      expect(html).toContain('Page Header')
      expect(html).toContain('Info Card')
      expect(html).toContain('Details here')
    })
  })

  describe('theme options', () => {
    it('supports light theme', () => {
      const lightRenderer = new UIPrototypeRenderer({ theme: 'light' })
      const html = lightRenderer.renderWireframe([{
        name: 'Light', title: 'Light Page', layout: 'single-column', components: [],
      }])
      expect(html).toContain('#ffffff')
      expect(html).toContain('#1a1a1a')
    })

    it('supports custom accent color', () => {
      const customRenderer = new UIPrototypeRenderer({ accentColor: '#ff6b35' })
      const html = customRenderer.renderDashboard({
        title: 'Custom', nav: [], widgets: [{ title: 'M', type: 'metric', data: { value: '42', label: 'x' } }],
      })
      expect(html).toContain('#ff6b35')
    })
  })

  describe('escapes HTML', () => {
    it('escapes special characters in content', () => {
      const html = renderer.renderWireframe([{
        name: 'XSS',
        title: 'Test <script>',
        layout: 'single-column',
        components: [{ type: 'card', title: '<img onerror="alert(1)">' }],
      }])
      // Angle brackets should be escaped, making script injection impossible
      expect(html).not.toContain('<script>')
      expect(html).toContain('&lt;script&gt;')
      expect(html).toContain('&lt;img')
      expect(html).toContain('&gt;')
      // Quotes should be escaped
      expect(html).toContain('&quot;')
    })
  })
})
