// SCALE Engine - External Skills Registration
import type { SkillDefinition, SkillRegistry } from './SkillRegistry.js'
import type { IEventBus } from '../core/eventBus.js'
import { workflowAgentSkillDefinitions } from './SkillCatalog.js'

export function registerExternalSkills(registry: SkillRegistry, eventBus: IEventBus): void {
  const skills: SkillDefinition[] = [
    { id: 'web-access', name: 'Web Access', description: 'CDP browser automation for web search, logged-in pages, and dynamic browser tasks', domain: 'execution', triggers: [{ type: 'taskType', value: ['web-scraping', 'web-research'], weight: 1.0 }, { type: 'keyword', value: ['browser', 'login', 'dynamic page', 'web-access'], weight: 0.9 }], execution: { type: 'skill-file', config: { skillPath: '~/.agents/skills/web-access/SKILL.md' } }, priority: 90, installed: true, source: 'https://github.com/eze-is/web-access' },
    { id: 'agent-browser', name: 'Agent Browser', description: 'Browser automation CLI for AI agents', domain: 'execution', triggers: [{ type: 'taskType', value: ['browser-automation', 'e2e-testing'], weight: 1.0 }, { type: 'keyword', value: ['agent-browser', 'browser automation', 'screenshot'], weight: 0.9 }], execution: { type: 'cli-command', config: { command: 'npx @agent-browser/cli' } }, priority: 86, installed: false, source: 'https://github.com/vercel-labs/agent-browser' },
    { id: 'mcp-chrome-devtools', name: 'Chrome DevTools MCP', description: 'Chrome DevTools MCP for browser inspection, console, and network evidence', domain: 'verification', triggers: [{ type: 'taskType', value: ['browser-automation', 'ui-debugging', 'e2e-testing'], weight: 1.0 }, { type: 'keyword', value: ['chrome devtools', 'cdp', 'console', 'network'], weight: 0.9 }], execution: { type: 'mcp-tool', config: { toolName: 'chrome-devtools' } }, priority: 88, installed: false, source: 'https://github.com/ChromeDevTools/chrome-devtools-mcp' },
    { id: 'playwright', name: 'Playwright', description: 'CLI browser automation', domain: 'execution', triggers: [{ type: 'taskType', value: ['e2e-testing'], weight: 0.9 }], execution: { type: 'skill-file', config: { skillPath: '~/.claude/skills/playwright/SKILL.md' } }, priority: 75, installed: true },
    { id: 'playwright-interactive', name: 'Playwright Interactive', description: 'Persistent session UI debug', domain: 'verification', triggers: [{ type: 'taskType', value: ['ui-debugging'], weight: 0.95 }], execution: { type: 'skill-file', config: { skillPath: '~/.claude/skills/playwright-interactive/SKILL.md' } }, priority: 80, installed: true },
    { id: 'cua', name: 'CUA', description: 'Computer use agent for desktop automation and GUI testing', domain: 'execution', triggers: [{ type: 'taskType', value: ['desktop-automation'], weight: 1.0 }, { type: 'keyword', value: ['desktop', 'gui', 'wps', 'wechat', 'computer use'], weight: 0.9 }], execution: { type: 'cli-command', config: { command: 'npx @anthropic/mcp-cua' } }, priority: 90, installed: false, source: 'https://github.com/trycua/cua' },
    { id: 'awesome-design-md', name: 'Awesome Design.md', description: 'DESIGN.md brand and product design system references', domain: 'planning', triggers: [{ type: 'taskType', value: ['ui-design'], weight: 1.0 }, { type: 'keyword', value: ['design system', 'brand', 'visual identity'], weight: 0.9 }], execution: { type: 'skill-file', config: { skillPath: '~/.agents/skills/awesome-design-md/SKILL.md' } }, priority: 88, installed: true, source: 'https://github.com/VoltAgent/awesome-design-md' },
    { id: 'ui-ux-pro-max', name: 'UI/UX Pro Max', description: 'UX guidelines and design intelligence database', domain: 'planning', triggers: [{ type: 'taskType', value: ['ui-design'], weight: 0.95 }, { type: 'keyword', value: ['ui', 'ux', 'accessibility', 'responsive'], weight: 0.9 }], execution: { type: 'skill-file', config: { skillPath: '~/.agents/skills/ui-ux-pro-max/SKILL.md' } }, priority: 89, installed: true, source: 'https://github.com/nextlevelbuilder/ui-ux-pro-max-skill' },
    { id: 'codex-cli', name: 'Codex CLI', description: 'External Codex CLI reviewer or worker', domain: 'verification', triggers: [{ type: 'taskType', value: ['external-agent-review'], weight: 1.0 }, { type: 'keyword', value: ['codex', 'codex cli'], weight: 0.9 }], execution: { type: 'cli-command', config: { command: 'codex --version' } }, priority: 76, installed: false, source: 'https://github.com/openai/codex' },
    { id: 'gemini-cli', name: 'Gemini CLI', description: 'External Gemini CLI reviewer or worker', domain: 'verification', triggers: [{ type: 'taskType', value: ['external-agent-review'], weight: 1.0 }, { type: 'keyword', value: ['gemini', 'gemini cli'], weight: 0.9 }], execution: { type: 'cli-command', config: { command: 'gemini --version' } }, priority: 74, installed: false, source: 'https://github.com/google-gemini/gemini-cli' },
    { id: 'opencode-cli', name: 'OpenCode CLI', description: 'External OpenCode CLI reviewer or worker', domain: 'verification', triggers: [{ type: 'taskType', value: ['external-agent-review'], weight: 1.0 }, { type: 'keyword', value: ['opencode', 'open code'], weight: 0.9 }], execution: { type: 'cli-command', config: { command: 'opencode --version' } }, priority: 74, installed: false, source: 'https://github.com/sst/opencode' },
    { id: 'graphify', name: 'Graphify', description: 'Knowledge graph generator', domain: 'context', triggers: [{ type: 'taskType', value: ['knowledge-graph'], weight: 1.0 }], execution: { type: 'skill-file', config: { skillPath: '~/.claude/skills/graphify/SKILL.md' } }, priority: 90, installed: true },
    // 未安装技能（SkillInstaller 可交互式安装）
    { id: 'fireworks-tech-graph', name: 'Fireworks Tech Graph', description: 'Tech flow diagrams', domain: 'planning', triggers: [{ type: 'taskType', value: ['diagram'], weight: 1.0 }], execution: { type: 'skill-file', config: { skillPath: '~/.claude/skills/fireworks-tech-graph/SKILL.md' } }, priority: 82, installed: false, source: 'https://github.com/yizhiyanhua-ai/fireworks-tech-graph' },
    { id: 'excalidraw-diagram-generator', name: 'Excalidraw Generator', description: 'Hand-drawn style diagrams', domain: 'planning', triggers: [{ type: 'taskType', value: ['sketch-diagram'], weight: 0.9 }], execution: { type: 'skill-file', config: { skillPath: '~/.claude/skills/excalidraw-diagram-generator/SKILL.md' } }, priority: 78, installed: false, source: 'https://github.com/github/awesome-copilot/tree/main/skills/excalidraw-diagram-generator' },
    { id: 'architecture-diagram-generator', name: 'Architecture Diagram', description: 'System architecture diagrams', domain: 'planning', triggers: [{ type: 'taskType', value: ['architecture-diagram'], weight: 1.0 }], execution: { type: 'skill-file', config: { skillPath: '~/.claude/skills/architecture-diagram-generator/SKILL.md' } }, priority: 85, installed: false, source: 'https://github.com/Cocoon-AI/architecture-diagram-generator' },
    { id: 'hyperframes', name: 'Hyperframes', description: 'HeyGen video generation', domain: 'execution', triggers: [{ type: 'taskType', value: ['video-generation'], weight: 1.0 }], execution: { type: 'cli-command', config: { command: 'npx @heygen/hyperframes' } }, priority: 75, installed: false, source: 'https://github.com/heygen-com/hyperframes' },
    { id: 'guizang-ppt-skill', name: 'Guizang PPT', description: 'PPT auto generation', domain: 'execution', triggers: [{ type: 'taskType', value: ['ppt-generation'], weight: 1.0 }], execution: { type: 'skill-file', config: { skillPath: '~/.claude/skills/guizang-ppt-skill/SKILL.md' } }, priority: 70, installed: false, source: 'https://github.com/op7418/guizang-ppt-skill' },
    ...workflowAgentSkillDefinitions(),
  ]
  registry.registerBatch(skills)
  eventBus.emit('external-skills.registered', { count: skills.length })
}
