# Generated by scale-engine governance pack: node-library@2
# Edit policy: prefer editing the pack in scale-engine; local overrides should be documented.

$ErrorActionPreference = 'Stop'
if (Get-Variable -Name PSNativeCommandUseErrorActionPreference -ErrorAction SilentlyContinue) {
  $PSNativeCommandUseErrorActionPreference = $false
}

$ProjectRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$Errors = 0
$Warnings = 0

function Note-Ok([string]$Message) {
  Write-Host "[OK] $Message"
}

function Note-Warn([string]$Message) {
  $script:Warnings++
  Write-Host "[WARN] $Message"
}

function Note-Error([string]$Message) {
  $script:Errors++
  Write-Host "[ERROR] $Message"
}

function Test-JsonFile([string]$Path) {
  try {
    $raw = Get-Content -Raw $Path
    $clean = $raw.TrimStart([char]0xFEFF)
    $null = $clean | ConvertFrom-Json
    return $true
  } catch {
    return $false
  }
}

function Test-PackageScript([string]$Name) {
  $pkg = Get-Content -Raw (Join-Path $ProjectRoot 'package.json') | ConvertFrom-Json
  return $null -ne $pkg.scripts.$Name
}

Write-Host '========================================'
Write-Host '[PREFLIGHT] node-library workflow'
Write-Host '========================================'
Write-Host ''

Write-Host '[CHECK] required tools'
if (Get-Command git -ErrorAction SilentlyContinue) {
  Note-Ok 'git'
} else {
  Note-Error 'git is required'
}

$Node = Get-Command node -ErrorAction SilentlyContinue
if ($Node) {
  Note-Ok ("node " + (node --version))
} else {
  Note-Error 'node is required'
}

$Npm = Get-Command npm -ErrorAction SilentlyContinue
$Pnpm = Get-Command pnpm -ErrorAction SilentlyContinue
if ($Npm) {
  Note-Ok ("npm " + (npm --version))
} elseif ($Pnpm) {
  Note-Ok ("pnpm " + (pnpm --version))
} else {
  Note-Error 'npm or pnpm is required'
}
Write-Host ''

Write-Host '[CHECK] optional tools'
foreach ($Tool in @('bash', 'rg', 'jq', 'gh', 'graphify', 'python', 'python3')) {
  if (Get-Command $Tool -ErrorAction SilentlyContinue) {
    Note-Ok $Tool
  } else {
    Note-Warn "$Tool is not installed"
  }
}
Write-Host ''

Write-Host '[CHECK] required directories'
foreach ($Dir in @(
  '.scale',
  '.planning\tasks',
  'docs\workflow',
  'docs\workflow\templates',
  'docs\worklog',
  '.claude\hooks',
  'scripts\gates',
  'scripts\hooks',
  'scripts\preflight',
  'scripts\qa',
  'scripts\workflow',
  'src',
  'tests'
)) {
  if (Test-Path (Join-Path $ProjectRoot $Dir)) {
    Note-Ok $Dir
  } else {
    Note-Error "missing directory: $Dir"
  }
}
Write-Host ''

Write-Host '[CHECK] governance JSON files'
foreach ($File in @(
  '.scale\verification.json',
  '.scale\workspace.json',
  '.scale\skills.json',
  '.scale\tools.json',
  '.scale\resource-policy.json',
  '.scale\assets.json',
  '.scale\output-policy.json',
  '.scale\product-smoke.json',
  '.scale\engineering-standards.json',
  '.scale\engineering-standards-baseline.json',
  '.scale\frameworks.json',
  '.scale\governance.lock.json'
)) {
  $Path = Join-Path $ProjectRoot $File
  if (-not (Test-Path $Path)) {
    Note-Error "missing JSON file: $File"
    continue
  }
  if (Test-JsonFile $Path) {
    Note-Ok $File
  } else {
    Note-Error "invalid JSON: $File"
  }
}
Write-Host ''

Write-Host '[CHECK] key workflow docs'
foreach ($File in @(
  'docs\workflow\README.md',
  'docs\workflow\node-library.md',
  'docs\worklog\metrics.md'
)) {
  if (Test-Path (Join-Path $ProjectRoot $File)) {
    Note-Ok $File
  } else {
    Note-Error "missing file: $File"
  }
}
Write-Host ''

Write-Host '[CHECK] package scripts'
foreach ($ScriptName in @('build', 'lint', 'test', 'typecheck')) {
  if (Test-PackageScript $ScriptName) {
    Note-Ok "package.json scripts.$ScriptName"
  } else {
    Note-Error "missing package.json script: $ScriptName"
  }
}
Write-Host ''

Write-Host '[CHECK] gate wrappers'
$GateScript = Join-Path $ProjectRoot 'scripts\gates\all.ps1'
if (Test-Path $GateScript) {
  $null = [System.Management.Automation.Language.Parser]::ParseFile($GateScript, [ref]$null, [ref]$null)
  if ($?) {
    Note-Ok 'scripts/gates/all.ps1 syntax'
  } else {
    Note-Error 'scripts/gates/all.ps1 is invalid'
  }
} else {
  Note-Error 'missing scripts/gates/all.ps1'
}
Write-Host ''

Write-Host '========================================'
if ($Errors -eq 0) {
  Write-Host "[PREFLIGHT] PASSED with $Warnings warning(s)"
  exit 0
}

Write-Host "[PREFLIGHT] FAILED with $Errors error(s), $Warnings warning(s)"
exit 1
